### ISSUE TITLE
k2cli Getting Started Guide Document Updates

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/k2cli#100]
Walking through `k2cli` today I made the following updates to sync the getting started guide with the user experience.  

-- minor editorial grammatical changes
-- defaults are out of date with generated config
-- yaml path needed to be corrected in a couple of places.
-- example commands can't be copy-pasta'd in to a terminal and run as is, need to be corrected to reflect installed configuration.

I also added an optional configuration section to explain to myself how to setup my initial cluster in a  region other than us east and that didn't have 10 c4.large nodes to start with.

**Comment by sostheim** [comment]
Related to the general condition of documents being out of date here #88 and #91.  But more specifically updates the project readme / getting started guide, not the cobra generated cmd reference documentation.

**Comment by coffeepac** [comment]
work was done?

**Comment by sostheim** [comment]
Yes, work was as done as it was going to be for this specific issue.
