### ISSUE TITLE
Make kubectl and helm subcommands handle the config file the same way as down/info/up/update

### ISSUE THREAD

**Issue by NathanZook** [samsung-cnct/k2cli#105]
k2cli kubectl & helm differ in their PreRunE functions from down/info/up/update in that they do not use `$HOME/.kraken/config.yaml` as the default value for PreRunE.  Otherwise, all of these functions are identical.

I propose that they should have the same behavior.  This relates to #99.

Also, they should all be calling one function so we don't get more drift...

**Comment by alejandroEsc** [comment]
Resolved in previous refactoring PR.
