### ISSUE TITLE
Feature Request: Change Default panic() Behavior for Handled Errors

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/k2cli#106]
The most common 4 lines of code in k2cli is, by far:
```
if err != nil {
    fmt.Println(err)
    panic(err)
}
```
In my experience, this is very much a Go anti-pattern.  

See for reference:
https://blog.golang.org/error-handling-and-go - in context here, `panic` is only ever mentioned as a thing that should be `recover`-ed from.  

https://blog.golang.org/defer-panic-and-recover
> The convention in the Go libraries is that even when a package uses panic internally, its external API still presents explicit error return values.

**Comment by sostheim** [comment]
Let me first say that, looking at the code, I realize what a significant change this would be.  

Second, I would like to understand the motivation for the current model.  Given the consistency in implementation, it's hard to imagine that this hasn't been a subject of discussion previously.  

Third, this is a very low priority request.  

However, having just used `k2cli` in earnest for the first time over the course of the last week, I find this behavior disconcerting to the user.  Every time I make a mistake of some sort, or some action intrinsic to the processing of my command/subcommand fails, I'm greeted with a panic stack trace.  A useful error message and clean exit would seem much more desirable to the end user.

**Comment by davidewatson** [comment]
Wow. There are quite a few panics (29!), and as you say, it's poor form.

I spent some time thinking about user interfaces, logging, and error handling recently in the context of careen. Some of the rules of thumb I decided on were: 1) Prefer to return errors without printing _anything_, except for at the top level command, when you are implementing an interface, 2) if you are printing something, print it to stderr/stdout, 3) never print warnings or errors, only informational messages which are meaningful to the user (and maybe debugging information if it's enabled by an option), 4) libraries should (almost) never panic, etc. I realize that some of these decisions are philosophical stances. Anyway, squirrel!

We should definitely see if we can start cleaning these up over time.

**Comment by coffeepac** [comment]
This looks like something to do with intent during 0.4.  We should use this issue to track the plan.  There are several other go apps being out together now that could use this direction.

**Comment by coffeepac** [comment]
Broadly: we should be using a standard error handling function and that panic is bad form.  We can and maybe should dump the panics now.  Even swapping from panics to logging the error would be easy.  Not the full goal but a good quick step.

**Comment by alejandroEsc** [comment]
+1 to brining up this concern.
