### ISSUE TITLE
k2cli hangs on image pull during cluster creation

### ISSUE THREAD

**Issue by notjames** [samsung-cnct/k2cli#118]
**Is this a BUG REPORT or FEATURE REQUEST?** 
BUG REPORT -- needs more investigation. Opening issue to track progress.

**k2cli version** (use `k2cli version`):
1.0.5-alpha+git.sha.e04ae0d98289565ab71424fd7b83072bfaed8f66 

**Environment**:
export K2OPTS="-e HOME=/Users/jimconn -e HELM_HOME=/Users/jimconn/.kraken/jimconn-test/.helm -e KUBECONFIG=/Users/jimconn/.kraken/jimconn-test/admin.kubeconfig --rm=true -it -v /Users/jimconn/.kraken:/Users/jimconn/.kraken -v /Users/jimconn/.ssh/id_rsa:/Users/jimconn/.ssh/id_rsa -v /Users/jimconn/.ssh/id_rsa.pub:/Users/jimconn/.ssh/id_rsa.pub -v /Users/jimconn/.aws/config:/Users/jimconn/.aws/config -v /Users/jimconn/.aws/credentials:/Users/jimconn/.aws/credentials" 

- **Environment variables** (e.g. `env | grep 'KRAKEN_`):
- **Configuration files (`~/.kraken/config.yaml` or the file passed to `k2cli --config`) **:
- **Others**:

**What happened**:
`k2cli cluster up` starts to pull image and image pull never completes (waited for ~10 mins before killing k2cli). Ran command on more than one attempt and the same results over the same approx period of time.

**What you expected to happen**:
Image pull, run, etc...

**How to reproduce it** (as minimally and precisely as possible):
Possible steps: from fresh vanilla OS install (in this case, OSX), run through https://github.com/samsung-cnct/k2 README.md to completion. Then, run k2cli steps. See if the issue will reproduce. This is how I managed to cause the issue as best as I can recall.

**Anything else we need to know**:

**Comment by notjames** [comment]
Steps I had to take in order to get k2cli to work -- I had to remove all images related to k2. Running k2cli in verbose mode eventually failed with an error that "jimconn-test-k2" image already existed.

**Comment by coffeepac** [comment]
what was the exact command you were using with k2cli?

**Comment by notjames** [comment]
`k2cli cluster up`

**Comment by coffeepac** [comment]
strange, that shouldn't have been trying to use a non-default image.  ie:  it should have been using `quay.io/samsung_cnct/k2:latest`, not `jimconn-test-k2`.

are you still able to produce this output or did you workaround clear the problem for keeps?

**Comment by notjames** [comment]
I'm working the issue right now. I'll follow-up with you as soon as I get some data.

**Comment by notjames** [comment]
The following tests were conducted using https://github.com/samsung-cnct/k2 README.md as a go-by:
* Skipped the stuff for setting up my environment. I already have the yams config and AWS credentials.
1. After running the k2cli issue on Friday, successfully, nothing done to docker images.
2. Today, opened issue #110
3. There were two images on the system before conducting the test:
```
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
quay.io/samsung_cnct/k2   latest              631138b0125c        3 days ago          887MB
quay.io/samsung_cnct/k2   <none>              a40f628a1f7e        4 days ago          887MB 
```
4. Ran the following: 
```
docker run $K2OPTS quay.io/samsung_cnct/k2:latest ./up.sh --config $HOME/.kraken/config.yaml
```
5. Received the following failure:
```
TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Check for terraform success] *****************************************************************************************************************************************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Run cluster up failed!"}

PLAY RECAP *****************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=121  changed=51   unreachable=0    failed=1

WARNING: Some of the cluster state MAY be available:
To use kubectl:
---------------

    kubectl --kubeconfig=/Users/jimconn/.kraken/jimconn-test/admin.kubeconfig <kubectl command>

To use helm:
------------

    KUBECONFIG=/Users/jimconn/.kraken/jimconn-test/admin.kubeconfig HELM_HOME=/Users/jimconn/.kraken/jimconn-test/.helm helm <helm command>

To ssh:

    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config etcd-1
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config etcd-2
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config etcd-3
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config etcd-4
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config etcdEvents-1
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config etcdEvents-2
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config etcdEvents-3
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config etcdEvents-4
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config master-1
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config master-2
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config clusterNodes-1
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config clusterNodes-2
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config clusterNodes-3
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config clusterNodes-4
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config clusterNodes-5
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config clusterNodes-6
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config clusterNodes-7
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config clusterNodes-8
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config clusterNodes-9
    ssh -F /Users/jimconn/.kraken/jimconn-test/ssh_config specialNodes-1
```
6. There might be some disparity between images. I ran the following:
```
$ docker pull quay.io/samsung_cnct/k2:latest
latest: Pulling from samsung_cnct/k2
280aca6ddce2: Already exists 
35247549c760: Already exists 
e9b0e9ccfd7e: Already exists 
b2aa3f5c1f19: Already exists 
ce29b3efc4f1: Already exists 
078afb862953: Already exists 
39f9bc1acaea: Already exists 
77d492849ec7: Already exists 
ba7c9f98c49d: Already exists 
66407a502897: Already exists 
44736315c8a7: Already exists 
d416fc85e20e: Already exists 
7c8f4ff60e37: Already exists 
334a9efe102a: Already exists 
6f5e4548c863: Already exists 
c89a8613a254: Already exists 
5721345c6406: Already exists 
20ab0421afa7: Already exists 
b6eab276f3f4: Already exists 
ebcbd6242436: Already exists 
1fad1b24c170: Already exists 
80b1802a5587: Already exists 
d0c58624dad5: Already exists 
cdb361c18800: Already exists 
c27b93366051: Already exists 
cf48a2bdaae2: Already exists 
fc76736e4e20: Pull complete 
Digest: sha256:f6d61ee084f940f8a3fec5575177145eee210ce62e9365d41d991eda590120dd
Status: Downloaded newer image for quay.io/samsung_cnct/k2:latest
14:47:11-jimconn~/.kraken$ docker images
REPOSITORY                TAG                 IMAGE ID            CREATED             SIZE
quay.io/samsung_cnct/k2   latest              44de1d91fca5        18 hours ago        887MB
quay.io/samsung_cnct/k2   <none>              631138b0125c        3 days ago          887MB
quay.io/samsung_cnct/k2   <none>              a40f628a1f7e        4 days ago          887MB
```
7. So docker pull pulled another image with a different image ID. Not a big deal, so re-ran the `./up.sh` script.
8. Failed with the same error as above.
9. Running docker container interactively and running ./up.sh after giving ansible playbook `debug` flag, I’m getting a clue now as the problem for this specific issue at least:
```
TASK [/kraken/ansible/roles/kraken.provider/kraken.provider.aws : Run cluster up] ************************************************************************************************************************************************************************************************************************************************************************************************************************************
FAILED - RETRYING: Run cluster up (10 retries left).
FAILED - RETRYING: Run cluster up (9 retries left).
FAILED - RETRYING: Run cluster up (8 retries left).
FAILED - RETRYING: Run cluster up (7 retries left).
FAILED - RETRYING: Run cluster up (6 retries left).
FAILED - RETRYING: Run cluster up (5 retries left).
FAILED - RETRYING: Run cluster up (4 retries left).
FAILED - RETRYING: Run cluster up (3 retries left).
FAILED - RETRYING: Run cluster up (2 retries left).
FAILED - RETRYING: Run cluster up (1 retries left).
fatal: [localhost]: FAILED! => {"attempts": 10, "changed": true, "cmd": ["terraform", "apply", "-input=false", "-no-color", "/Users/jimconn/.kraken/jimconn-test"], "delta": "0:00:00.485047", "end": "2017-07-18 22:02:26.713269", "failed": true, "rc": 1, "start": "2017-07-18 22:02:26.228222", "stderr": "Errors:\n\n  * file: read /Users/jimconn/.ssh/id_rsa.pub: is a directory in:\n\n${file(\"/Users/jimconn/.ssh/id_rsa.pub\")}", "stderr_lines": ["Errors:", "", "  * file: read /Users/jimconn/.ssh/id_rsa.pub: is a directory in:", "", "${file(\"/Users/jimconn/.ssh/id_rsa.pub\")}"], "stdout": "There are warnings and/or errors related to your configuration. Please\nfix these before continuing.", "stdout_lines": ["There are warnings and/or errors related to your configuration. Please", "fix these before continuing."]}
...ignoring
```
10. I recall having a similar issue with this when I first ran through the docs while on boarding, but quickly dismissed it thinking I did something wrong. I fixed it and was able to properly bring up the cluster. It’s suspicious to me now that this is happening again.
```
15:07:36-jimconn~/.ssh$ ls -altr
total 32
-rw-r--r--   1 jimconn  staff   756 Jul  5 15:38 github-id_rsa.pub
-rw-------   1 jimconn  staff  3243 Jul  5 15:38 github-id_rsa
-rw-r--r--   1 jimconn  staff  1018 Jul 11 15:30 known_hosts
-rw-r--r--   1 jimconn  staff    35 Jul 17 15:10 config
drwxr-xr-x+ 50 jimconn  staff  1700 Jul 17 17:26 ..
drwxr-xr-x@  2 jimconn  staff    68 Jul 18 14:27 id_rsa.pub  <— directory
drwxr-xr-x@  2 jimconn  staff    68 Jul 18 14:27 id_rsa.     <— directory
```
11. I did replace my original id_rsa[.pub] files a couple of days ago. So something is going in and creating a directory with these names instead of failing.
12. Recreating my ssh keys and running the cluster up again and that succeeded. OK. Take-away: better UX when their environment is not properly set up.

however, this does not properly reproduce the issue Sam and I were experiencing last week. So, moving forward with more testing.

**Comment by notjames** [comment]
I strongly suspect the culprit of the directories being created are from my `$K2OPTS` exporting a docker volume of `-v /Users/jimconn/.ssh/id_rsa:/Users/jimconn/.ssh/id_rsa -v /Users/jimconn/.ssh/id_rsa.pub:/Users/jimconn/.ssh/id_rsa.pub -v /Users/jimconn/.aws/credentials:/Users/jimconn/.aws/credentials` after thinking about what the `-v` switch does. It should be exporting the directory itself, not files. I'll have to track down the documentation that specified to do that (I think it's in the onboarding docs somewheres).

**Comment by notjames** [comment]
https://github.com/samsung-cnct/k2 in README.md under `Preparing the environment`...should the env be:

```
KRAKEN=${HOME}/.kraken                  # This is the default output directory for K2
SSH_KEY=${HOME}/.ssh/id_rsa           # This is the default rsa key configured
AWS_CONFIG=${HOME}/.aws/config  # Use these files when using the aws provider
SSH_ROOT=${HOME}/.ssh
SSH_PUB=${HOME}/.ssh/id_rsa.pub
AWS_ROOT=${HOME}/.aws
AWS_CREDENTIALS=${HOME}/.aws/credentials
K2OPTS="-v ${KRAKEN}:${KRAKEN}
        -v ${SSH_ROOT}:${SSH_ROOT}
        -v ${AWS_ROOT}:${AWS_ROOT}
        -e HOME=${HOME}
        --rm=true
        -it"
```

**Comment by notjames** [comment]
So far, I'm unable to reproduce the hanging of k2cli on image pull during cluster creation.

**Comment by coffeepac** [comment]
going to close as its been 8 days.  if this happens again please re-open and we'll get investigating again.
