### ISSUE TITLE
Filepath cleanup for K2 shell scripts

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/k2cli#124]
As per https://github.com/samsung-cnct/k2/pull/718, all shell scripts now live in a `bin` directory. File path references to these scripts within k2cli must be appropriately adjusted.

**Comment by guineveresaenger** [comment]
Upon going through these, it appears as though k2cli calls the actual shell scripts in some cases, but for up/update/down, it calls the .yaml files in k2/ansible. We should probably fix that for conformity and ease of maintenance. 
Issue filed [here](https://github.com/samsung-cnct/k2cli/issues/124)

**Comment by leahnp** [comment]
Are we waiting on #126 to be merged to close this?

**Comment by coffeepac** [comment]
yes
