### ISSUE TITLE
Add ability to use tags (eg. dryrun)

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#130]
**Is this a BUG REPORT or FEATURE REQUEST?** (choose one): Feature request

**kraken (k2cli) version**:
```
1.0.7-stable+git.sha.d7454e05aab6b0a3078b660fb44497dfa25a853a
```
The underlying shell scripts support the passing of a tags parameter to limit the actions to a specific subset, for instance `dryrun` will not perform actions that require a working provider.

Please add the ability to use the `--tags` switch.

**Comment by alejandroEsc** [comment]
already implemented called stages, but this doesnt make sense, or well rather kinda make sense. I will rename the variable with its expected shorthand. Stages will still behave as usually but will also allow you to do the tags you need. Default is all.
