### ISSUE TITLE
Required: Thematic Easter Egg

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#132]
_From @jandrake on August 14, 2017 23:30_

The newly renamed from k2cli kraken interface needs an easter egg that is thematic...

kraken --release-me

or

kraken --release-the

Should result in an easter TBD and modified from time to time by internal kraken contributors.

Please note: must adhere to all Samsung proprieties, within reason.

_Copied from original issue: samsung-cnct/k2#748_

**Comment by joejulian** [comment]
_From @DStorck on August 14, 2017 23:31_

that is excellent.

**Comment by joejulian** [comment]
I totally agree!

Please refile in https://github.com/samsung-cnct/k2cli/issues

**Comment by guineveresaenger** [comment]
Yes please! :D
