### ISSUE TITLE
tool action does not find new script location

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#133]
_From @joejulian on August 15, 2017 15:58_

With the scripts having been moved, this now occurs:
1.0.7-stable+git.sha.d7454e05aab6b0a3078b660fb44497dfa25a853a

```
k2cli tool kubectl --config ~/.kraken/jj-r53.yaml get nodes
Using K2 config file: /home/jjulian/.kraken/jj-r53.yaml
Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"./computed_kubectl.sh\": stat ./computed_kubectl.sh: no such file or directory"
panic: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"./computed_kubectl.sh\": stat ./computed_kubectl.sh: no such file or directory"
```

_Copied from original issue: samsung-cnct/k2#754_

**Comment by davidewatson** [comment]
Is it possible this is from an old version of `k2cli?

````
rodin:k2cli dwat$ grep computed  cmd/*
cmd/kubectl.go:		command := []string{"/kraken/bin/computed_kubectl.sh", k2Config}
rodin:k2cli dwat$ 
```

**Comment by guineveresaenger** [comment]
@dwat the quoted code is new. It is actually part of the move to bin. Do you see a potential problem?

**Comment by coffeepac** [comment]
need to build a new version of k2cli.  code was merged last week for this.

**Comment by davidewatson** [comment]
`k2cli` always downloads the latest `k2-tools` image. So either we failed to do a release, or the user needs to use brew to upgrade k2cli.

**Comment by coffeepac** [comment]
current version of k2cli is 1.0.7, we need 1.0.8.

**Comment by coffeepac** [comment]
new release cut:  https://github.com/samsung-cnct/k2cli/releases/tag/1.0.8

@joejulian please pull the latest release and try again.

**Comment by joejulian** [comment]
Different error now. Not sure if it's related yet.
```
/kraken/bin/max_k8s_version.sh: line 33: syntax error: unexpected end of file
```
looking in to it...

**Comment by joejulian** [comment]
Unrelated. Thanks.

**Comment by oneilcin** [comment]
I rebuilt the k2cli locally and get these errors (go version go1.8.3 darwin/amd64):
./k2cli tool kubectl --config /Users/cynthiaoneill/.kraken/config.yaml get nodes
Using K2 config file: /Users/cynthiaoneill/.kraken/config.yaml
/kraken/bin/max_k8s_version.sh: line 33: syntax error: unexpected end of file

Cynthias-MBP:k2cli cynthiaoneill$ ./k2cli version
Invalid character(s) found in major number "-alpha+git"
panic: Invalid character(s) found in major number "-alpha+git"

goroutine 1 [running]:
github.com/samsung-cnct/k2cli/cmd.glob..func20(0x1751dc0, 0x17753b0, 0x0, 0x0)
	/Users/cynthiaoneill/go/src/github.com/samsung-cnct/k2cli/cmd/version.go:36 +0x249
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).execute(0x1751dc0, 0x17753b0, 0x0, 0x0, 0x1751dc0, 0x17753b0)
	/Users/cynthiaoneill/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:636 +0x231
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x174fde0, 0x100644c, 0xc420072058, 0x0)
	/Users/cynthiaoneill/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x174fde0, 0x0, 0x47)
	/Users/cynthiaoneill/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/samsung-cnct/k2cli/cmd.Execute()
	/Users/cynthiaoneill/go/src/github.com/samsung-cnct/k2cli/cmd/root.go:65 +0x31
main.main()
	/Users/cynthiaoneill/go/src/github.com/samsung-cnct/k2cli/main.go:23 +0x22

**Comment by oneilcin** [comment]
I see the Makefile changed, will rebuild and test

**Comment by guineveresaenger** [comment]
@oneilcin there was a missing `fi` in that script: https://github.com/samsung-cnct/k2/pull/755
