### ISSUE TITLE
remove docs subcommand

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2cli#136]
**Note:** Please file issues for subcomponents under the appropriate repo

| Component | Repo                                                                           |
| --------- | ------------------------------------------------------------------------------ |
| k2        | [samsung-cnct/k2cli](https://github.com/samsung-cnct/k2cli/issues/new)         |
| k2-charts | [samsung-cnct/k2-charts](https://github.com/samsung-cnct/k2-charts/issues/new) |
| k2-tools  | [samsung-cnct/k2-tools](https://github.com/samsung-cnct/k2-tools/issues/new)   |

**What keywords did you search in k2cli issues before filing this one?** (If you have found any duplicates, you should instead reply there.):

---

**Is this a BUG REPORT or FEATURE REQUEST?** (choose one):
feature request

the docs subcommand writes out the help text for each subcommand as a markup file.  I don't see this as terrible useful and recommend removing the subcommand.
**k2cli version** (use `k2cli version`):
all

**Environment**:

Please be sure not to submit any confidential information (e.g. ssh keys, provider secrets, etc.) as issues are publicly accessible.

- **Environment variables** (e.g. `env | grep 'KRAKEN_`):
- **Configuration files (`~/.kraken/config.yaml` or the file passed to `k2cli --config`) **:
- **Others**:

**What happened**:

**What you expected to happen**:

**How to reproduce it** (as minimally and precisely as possible):

**Anything else we need to know**:

**Comment by alejandroEsc** [comment]
@coffeepac ill take this ticket if you dont mind, just want to look at a bit of go for a quick break.

**Comment by coffeepac** [comment]
I haven't gotten agreement from the rest of the team we want to do this.  so feel free!  but there may be some discussion about go/no-go for this

**Comment by guineveresaenger** [comment]
I've been wasting a bunch of time trying to get this into the k2cli CI process, and it seems as though it might be better to let it go? But I think last discussion we had was leaning towards generating docs with each merge to master. If these autogenerated docs seem not useful on the whole, though, I'll be happy to not do that work.

**Comment by coffeepac** [comment]
My apologies @guineveresaenger I thought we had agreed to handle the the doc updates in another issue then the one you are working on.

Please don't work on autogenerating these docs anymore.

**Comment by guineveresaenger** [comment]
No problem - I knew we were having this discussion so I haven't been working on it since it came up. However, I wasn't aware we were doing away with the entire docs command. What is the recommended alternative? I'm happy to create the new issue; I'm just now sure how we're proceeding.

**Comment by coffeepac** [comment]
will deal with doc generation in the nearihs future
