### ISSUE TITLE
command line options not taking effect

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#138]
**Is this a BUG REPORT or FEATURE REQUEST?**: BUG Report

**k2cli version** (use `k2cli version`): 1.0.8

**What happened**:

```bash
$ echo $PWD
/home/jjulian/dev/clusterx
$ k2cli -v --k2config $PWD/config.yaml --output $PWD/state tool kubectl get nodes
Using K2 config file: /home/jjulian/.kraken/config.yaml
WARNING: --output not specified. Using /home/jjulian/.kraken as location
...
```
At which point it goes on to run ansible instead of kubectl.

**What you expected to happen**:
My expectation was that it would use the config and output directory that I specified. I further expected to see the output of `kubectl get nodes`.

**How to reproduce it** (as minimally and precisely as possible):
As shown.

**Anything else we need to know**:
I believe the help text is wrong and that instead of `-k --k2config` it's actually `-c --config`.

![image](https://user-images.githubusercontent.com/952828/29348801-0012f7c0-820b-11e7-85aa-1f54a7867848.png)

**Comment by alejandroEsc** [comment]
I wont mind investigating, or helping out. To startin if you remove the $PWD and leave just ./ what happens?

**Comment by joejulian** [comment]
It will fail. Relative paths will not work with the way volume mapping is done to docker.

**Comment by joejulian** [comment]
```
$ k2cli -v --config $PWD/config.yaml --output $PWD/state tool kubectl get nodes
Using K2 config file: /home/jjulian/dev/clusterx/config.yaml
WARNING: --output not specified. Using /home/jjulian/.kraken as location
```

**Comment by joejulian** [comment]
Ok, I think this is it. The cobra config in `cmd/tool.go` overrides the supposedly global `cmd/root.go` instead of extending it.

**Comment by davidewatson** [comment]
Excessive use of globals and inconsistent handling of command line arguments is a significant motivator for https://github.com/samsung-cnct/k2cli/issues/112.

**Comment by alejandroEsc** [comment]
should be closed with https://github.com/samsung-cnct/k2cli/pull/140, please reopen if not.
