### ISSUE TITLE
named container cleanup doesn't always work

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2cli#22]
successfully created a cluster using k2cli.  I am attempting to run helm commands against that cluster using 'k2cli tool helm ...' and receiving the following error:

> k2cli pat$ k2cli tool helm --config /Users/pat/code/k2/clusters/pac-ebs-logs.1.yaml --output /Users/pat/code/k2/clusters list
Using k2 config file: /Users/pat/code/k2/clusters/pac-ebs-logs.1.yaml
Error response from daemon: Conflict. The name "/k2-pac-bag" is already in use by container 119733e9e15cfa7e5ba468bf5ba81c3eaa8da0e3d4e9e9240a557f3b9f9a1055. You have to remove (or rename) that container to be able to reuse that name.
panic: Error response from daemon: Conflict. The name "/k2-pac-bag" is already in use by container 119733e9e15cfa7e5ba468bf5ba81c3eaa8da0e3d4e9e9240a557f3b9f9a1055. You have to remove (or rename) that container to be able to reuse that name.

finding the container in docker looks like this:

> pat$ docker ps --all | grep bag
119733e9e15c        quay.io/samsung_cnct/k2:latest                      "kubectl get nodes"      41 minutes ago      Exited (1) 41 minutes ago                       k2-pac-bag

manually deleting the container allows the helm command to execute successfully once.  the container remains afterwards.

**Comment by coffeepac** [comment]
This seems to only affect the tool subcommand but it hits every time.  makes the tool command unusable, upping priority.

**Comment by maratoid** [comment]
FWIW, I couldn't reproduce this with:

```
k2cli tool helm --config ~/.kraken/zonar-cluster-creator.json help
...
docker ps -all
CONTAINER ID        IMAGE                             COMMAND             CREATED             STATUS                    PORTS               NAMES
```

**Comment by coffeepac** [comment]
Hrm..   I wonder if I'm doing something strange.  I'm running docker for mac v 1.12.3 and I was building k2cli off of master.  Lemme try it with the 1.0.1 build.

**Comment by coffeepac** [comment]
I am unable to reproduce this with version 1.0.1 or with my locally built version.  I suspect there is something wrong with the configuration file I was using originally.  Will rebuild the cluster with that one.

**Comment by coffeepac** [comment]
aannndd now I can't repro it at all.  okay, great.  I'm going to close this as a fluke of my system at the time.  I had nuked my private key but I thought I had fixed that at this point.  maybe not!  

anyway:  closing until we see this again.
