### ISSUE TITLE
k2cli can't handle local only image

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2cli#36]
doing k2 dev and wanted to have k2cli use a local-only image.  image tag was 'local/k2'.  able to run 'docker run -it local/k2 sh' and get a running container.  running 'k2cli cluster up <guff> -i local/k2' resulted in a go panic and the following error:

> Pulling image 'local/k2:latest' ███████▒▒▒ %v Error: image local/k2:latest not found
panic: Error: image local/k2:latest not found

what gives.  this should work.

**Comment by coffeepac** [comment]
this is probably a limitation of the underlying docker client

**Comment by coffeepac** [comment]
annoying but not going to work around the docker library limitation

**Comment by alejandroEsc** [comment]
I have gotten this to work before the latest docker release, so my suspicion aligns with yours.
