### ISSUE TITLE
`k2cli generate` does not work

### ISSUE THREAD

**Issue by spiffxp** [samsung-cnct/k2cli#37]
```
aaron@cloudtop:k2cli (master)$ k2cli generate
Pulling image 'quay.io/samsung_cnct/k2:latest' █████▒▒▒▒▒
Error response from daemon: invalid name: "k2-" includes invalid characters, resource name has to conform to "^[\\w]+[\\w-. ]*[\\w]+$"
panic: Error response from daemon: invalid name: "k2-" includes invalid characters, resource name has to conform to "^[\\w]+[\\w-. ]*[\\w]+$"
```

This may be a new error related to the version of docker I'm using?
```
aaron@cloudtop:k2cli (master)$ docker version | grep Version
 Version:      1.13.0-rc3
 Version:      1.13.0-rc3
```

The container that k2cli runs is supposed to be named after the cluster, but in the case of generate, there is no cluster yet, so there is no cluster name.  This results in the container being named "k2-" which my daemon seems to be rejecting.

Maybe just drop the whole idea of naming containers after their clusters.  I added it in, and I'm unsure if anyone has found it useful for troubleshooting.  Meanwhile we've had to workaround bugs it introduced.

**Comment by spiffxp** [comment]
Pretty sure this is related to docker 1.13.0.  I just ran `k2cli generate` with docker 1.12.0 and had no complaints

**Comment by coffeepac** [comment]
trying with docker-1.13.0-stable and issue persists.

**Comment by coffeepac** [comment]
docker 1.13.0 enforces a strict container naming pattern (^[\\w]+[\\w-. ]*[\\w]+$) which is violated during config generation.  the name is 'k2-<clustername>' where <clustername> is provided by the config file.  however, for a generated config that value is blank which means the clustername ends in a '-' which is no longer allowed.

**Comment by coffeepac** [comment]
resolved by:  https://github.com/samsung-cnct/k2cli/pull/42

when merged I'll release a new version of k2cli

**Comment by coffeepac** [comment]
new release cut:  https://github.com/samsung-cnct/k2cli/releases/tag/1.0.3

**Comment by coffeepac** [comment]
@spiffxp please test k2cli version 1.0.3 to see if this issue persists.  if it does, lemme know.

**Comment by spiffxp** [comment]
```
spiffxp@kthxbye:~$ k2cli version
1.0.3-alpha+git.sha.5e06aeda22c43c62ef0e7808723339b091ffa260
spiffxp@kthxbye:~$ k2cli generate
Pulling image 'quay.io/samsung_cnct/k2:latest' ██████████
Generated config at /Users/spiffxp/.kraken/config.yaml
spiffxp@kthxbye:~$ docker version
Client:
 Version:      1.13.0-rc7
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.13.0-rc7
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   48a9e53
 Built:        Fri Jan 13 21:41:57 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

works, closing
