### ISSUE TITLE
add support for use of `~/.aws/credentials` instead of `AWS_*` env vars

### ISSUE THREAD

**Issue by spiffxp** [samsung-cnct/k2cli#38]
k2 supports both options, but at the moment k2cli only supports / expects the usual set of `AWS_*` env vars

Ran into this on a new setup that only had `~/.aws/credentials` and no env vars

**Comment by coffeepac** [comment]
this also doesn't work in K2:  https://github.com/samsung-cnct/k2/issues/128

**Comment by joejulian** [comment]
`~` doesn't expand correctly. Use `${HOME}`.

**Comment by joejulian** [comment]
On the other hand, there are documentation changes that need made because this actually works.
