### ISSUE TITLE
tool ssh update panic

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#40]
$ k2cli tool ssh update                                                   
Pulling image 'quay.io/samsung_cnct/k2:latest' █████▒▒▒▒▒ 
Updating ssh inventory for '' panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x82f060, 0xc420010170)
	/usr/lib/go/src/runtime/panic.go:500 +0x1a1
github.com/samsung-cnct/k2cli/cmd.glob..func15(0xae4f80, 0xb098f8, 0x0, 0x0)
	/home/jjulian/.local/share/go/src/github.com/samsung-cnct/k2cli/cmd/ssh-update.go:50 +0xa24
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).execute(0xae4f80, 0xb098f8, 0x0, 0x0, 0xae4f80, 0xb098f8)
	/home/jjulian/.local/share/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:636 +0x443
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xae3e80, 0xc42017bee8, 0x40503b, 0xc4200180b8)
	/home/jjulian/.local/share/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:722 +0x367
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).Execute(0xae3e80, 0xc4200deb40, 0x0)
	/home/jjulian/.local/share/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/samsung-cnct/k2cli/cmd.Execute()
	/home/jjulian/.local/share/go/src/github.com/samsung-cnct/k2cli/cmd/root.go:63 +0x31
main.main()
	/home/jjulian/dev/k2cli/main.go:23 +0x22

**Comment by coffeepac** [comment]
dupe bug created #46   closing
