### ISSUE TITLE
makefile targets don't all work

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2cli#41]
the makefile targets 'build' and 'install' require that 'godep' be installed on the system.  godep isn't installed by the deps command.

what is godep?  is it still needed now that golang has native dependency management?  can we include it in the deps target so these other targets work?

**Comment by maratoid** [comment]
https://github.com/tools/godep

It IS the dependency management tool.

**Comment by coffeepac** [comment]
Party.  On.  Wayne.  

Sounds like it needs to be added an dependency then.

**Comment by coffeepac** [comment]
This should not be added to the Makefile.  This should be a modification of the README to say 'godep needs to be installed'.

**Comment by coffeepac** [comment]
won't fix
