### ISSUE TITLE
Change the default generated config.yaml to bind the aws files that are needed by K2

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#51]
https://github.com/samsung-cnct/k2/issues/181 breaks `config.yaml` if $HOME is referenced. The fix is to revert the creation of a temporary HOME and, instead, bind only the files K2 actually needs to /root.

k2cli should go through the config.yaml and bind any files that are configured to the correct places needed by K2.

**Comment by joejulian** [comment]
Heh, what do you know. k2cli already does this.

**Comment by joejulian** [comment]
Well, ok, there are a couple that are not.

**Comment by davidewatson** [comment]
LGTM.

**Comment by coffeepac** [comment]
what's the precedence for this?  does ENV var override the config file?  we'd want to maintain the same precedence that the [AWS docs list](http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html) (roughly, env > cli > aws config > aws cli config > iam)

**Comment by joejulian** [comment]
That's the plan

**Comment by coffeepac** [comment]
baller.  LGTM then.
