### ISSUE TITLE
is k2cli docs needed?

### ISSUE THREAD

**Issue by spiffxp** [samsung-cnct/k2cli#52]
I mean, I don't know what I was expecting, but it was a bit surprising when I ran `k2cli docs` and it spewed markdown files all over my CWD

This seems like something that should be part of the build process, not the tool itself?

**Comment by coffeepac** [comment]
this command dumps the normal command help out as markdown files.  I don't see a use for this actually.  these files almost certainly shouldn't be checked into github.

**Comment by coffeepac** [comment]
ToReview:
the listed PR and issue cover removal of the docs subcommand from this application
- PR to remove docs folder from github: https://github.com/samsung-cnct/k2cli/pull/137
- Issue to remove docs subcommand: https://github.com/samsung-cnct/k2cli/issues/136

**Comment by leahnp** [comment]
LGTM
