### ISSUE TITLE
create project start for k2cli manage node command

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2cli#54]
we need to support changing the version of a running kubernetes cluster without taking down the cluster.  this ticket will track creation of requirements and initial tickets to perform this work.

**Comment by coffeepac** [comment]
created an initial and very loose project requirement spec and sent to @l337ch and @cwazy1 for review.  spec was as follows:

>  k2cli node management
>
> k2cli should have a subcommand that allows for a predictable path for upgrading the version of kubernetes running on each node.  the
subcommand should be able to differentiate between kubelet nodes and control plane nodes.  this version changing process will do its 
best to be transparent to all end users but will have to operate within the confines of a specified pod.  IE: single pod applications
that have persistent disks will have an outage as they migrate.  Can't have two DB nodes with an exclusive write lock on the same disk.
Additionally, we will be using the 'drain' subcommand in kubectl (or its API equivalent).

**Comment by coffeepac** [comment]
received a +1 from @l337ch.  I suspect that's enough to get moving.  now to make sure this is sane with my team.

**Comment by leahnp** [comment]
How would we handle testing for this?

**Comment by coffeepac** [comment]
on an ad-hoc basis:  we would (from our desktops) manually exercise the functionality making sure we can go up and down in kubernetes version.  Kubernetes itself should be available the entire time.

on a permanent basis:  we would write an integration test to do this.  This would be a check outside of the current e2e conformance tests we run.

Note:  This does not cover upgrading or downgrading etcd versions.  That's a different kettle of wax.

**Comment by leahnp** [comment]
Sounds good, perhaps having a reoccurring ticket to check the test against new client's environments would help make the test continually more robust and less likely to cause problems in a production environment with an edge case we didn't consider.

**Comment by joejulian** [comment]
Is this higher priority than testing? As much as i hate writing tests, I have seen the value in unit/ci testing and would really like to see us progressing that way sooner rather than later.

**Comment by coffeepac** [comment]
@leahnp sounds good.  ideally that'd be something we could get the engagement team to either do or at least spec out.

**Comment by coffeepac** [comment]
@joejulian it is higher then our CI work and I'm loathe to start up a test writing cycle if we're about to overhaul our CI system.  You're not alone in asking for a focus on testing though, its something we are bad at.  My other priority right now is sorting out our CI approach.

**Comment by joejulian** [comment]
Then LGTM

**Comment by coffeepac** [comment]
Tickets to create:
- research spike for GKE node upgrades
-- output is list of commands to upgrade a nodepool
- research spike for AWS nodepool upgrades
-- output is list of commands to upgrade a kubelet nodepool
-- suggest using drain/destroy/create new node as version modification pattern
- research spike for AWS control plane upgrades
-- how compatible are API/Master/Scheduler processes across versions?
- design spec for config comparison munger
-- specified roughly [here](https://github.com/samsung-cnct/k2/issues/152#issuecomment-280458539)
-- should include if this lives in k2 or k2cli repo (or other, new repo and get baked into k2-tools).  should be written in go
- design spec for template versioning
-- same comment as above.

**Comment by coffeepac** [comment]
ToReview:
- tickets created (in k2 217, 218, 219, 221, 222)
-- covers the prior ticket
- ticket k2#223 to handle testing questions
- check that the above tickets covers what we need to get started and answers any open questions from this thread

**Comment by coffeepac** [comment]
team agreed during Sprint Planning meeting that we have asked sufficient questions to get started.  Done!
