### ISSUE TITLE
k2cli tool command should use correct version of tools

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2cli#67]
there are now going to be several versions of kubecl and helm installed onto the k2-tools image.  when attempting to execute the binary inside the image we should be certain to use the correct version as specified by the config file.

**Comment by venezia** [comment]
There's many k8s components in hyperkube (kubelet, apiserver, controller-manager, proxy, scheduler) - arguably we could have a different kubelet version than apiserver.  Should we pin this out intended apiserver version?

**Comment by coffeepac** [comment]
should be pinned to the version specified in the master config block.  this is a bit unspecific but we don't have the control plane components split out so its the best we can do.

**Comment by NathanZook** [comment]
I have been informed that GKE lacks master entirely.  David has suggested that we should take the latest version specified anywhere.  ???? @coffeepac

**Comment by davidewatson** [comment]
To clarify, I am suggesting the latest version specified by a nodePool within the same cluster.

**Comment by mikeln** [comment]
Ok.  So we should use whatever the version of Kubernetes the API server is running.  In our system the only way to know that is by looking for  `nodePools.name == master`.  We need to codify the **special** names in our system...especially `master`.   That is the correct way to be forward looking..in case we have different versions running on each node (I hope not).   

However, I agree, perhaps it is adequate to take the first  `deployment.clusters[0].nodePools[*].kubeConfig` value that you can find and get the `version` from there.

**Comment by davidewatson** [comment]
I am not convinced that we need a special name for nodes which have the role of master.

1) `nodePools.name == master` does not exist for GKE, so the nodePool name is not sufficient.

2) The AWS provider role does not assume a special nodePool named master (when it matters we check if `nodePool.apiServerConfig is defined`). This was a conscious design choice.

3) It is possible to have two different master nodes running different versions of k8s (c.f. rolling upgrades, testing, etc.)

If it turns out that the design choice was wrong, I'd rather invent a new property (say nodeType) and continue allowing names to be chosen by the user.

**Comment by mikeln** [comment]
ok, I like the `nodeType` idea... it is implicit in the system right now.

**Comment by coffeepac** [comment]
GKE has a master node but it is provided by GKE and we have no control over it.  

nodeType is most definitely a different issue.  I have been assuming that the `master` nodePool would always exist because most people would take a generated config and alter it.  A sloppy assumption but it seemed sufficient for now.  

Taking the first nodePool with a kubeConfig is probably sufficient but it would be preferable to interrogate the whole list of nodePools and find the kubeConfig with the most recent version.

**Comment by NathanZook** [comment]
Will take the highest present.

**Comment by NathanZook** [comment]
Blocked on https://github.com/samsung-cnct/k2/issues/498.

**Comment by NathanZook** [comment]
The implementation work on samsung-cnct/k2#498 (https://github.com/samsung-cnct/k2/pull/526) diverged substantially from initial plan.  samsung-cnct/k2#498 is now an unrelated feature request.

**Comment by coffeepac** [comment]
To Reaffirm for me as I get on this:  `k2cli tool kubectl` will use the highest major.minor version it can find in the nodepools to select which version of kubectl to use.

**Comment by davidewatson** [comment]
Yes. I believe we should always use the latest kubectl specified.

Medium term we need more CI testing in this area.

There are a few more bread crumbs [here](https://github.com/kubernetes/kubernetes/issues/33212).

**Comment by coffeepac** [comment]
need to fix `comupted_kubectl.sh` as it only works if called without an absolute path.  If you have a path on the call to the script the call to `mktemp` uses the entire application call so we need to either a: strip directories off of `$0` before using it in `mktemp` or don't use `$0` in the shell script.

**Comment by mikeln** [comment]
Hate to ask...but the actual implementation of this feels really convoluted... i.e.:  bash script -> bash script -> ansible -> write file -> pull in file -> return in pipe.  I expect there are some reasons for this, would like them to be more obvious in the script/code.

Other observations.. the 2nd bash script assumes arg $1 will be supplied, but doesn't do any validation of that.

**Comment by coffeepac** [comment]
I won't disagree.  The issue its hitting is not having config validation exist in more than one codebase and making the version information available in a general way (ie:  output to a file).  I believe the best long-term solution is moving config parsing to an external go lib that can be imported to either k2 or k2cli.  No issue for that though, I can file one if that will cover your first observation.

I can add some validation for $1 as part of this one.

**Comment by mikeln** [comment]
Ok.

**Comment by coffeepac** [comment]
config validation issue:  https://github.com/samsung-cnct/issues/issues/26

**Comment by coffeepac** [comment]
update PR to check that the variable is passed in and points to a file.  should be good?
