### ISSUE TITLE
Add verbose output to k2cli

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#68]
Add the ability to increase the verbosity of k2cli (k2 (ansible)) and have it display while it's running.

**Comment by NathanZook** [comment]
I don't know yet how we are bringing things up, but I think that messages along the lines of "2/3 etcd nodes up, 1/3 ready" would score really well both on the "actionable data" scale and on the "comfort" scale.

**Comment by leahnp** [comment]
Regarding the chatter on the slack channel - I think we should stick to the scope of this ticket and add functionality to allow users to choose:

-  no output (spinner when no verbosity is set)
-  -v default output (ansible tasks)
-  -vv verbose mode (ansible tasks and stack traces)

Niceties surrounding the spinner/etc should probably get it's own ticket.

**Comment by DStorck** [comment]
Sounds good @leahnp. I will go ahead and just add options for verbosity on this ticket, and add some pieces from the slack conversation to the issue about the progress bar.

**Comment by DStorck** [comment]
Currently able to have output displayed, but not in real time. Currently commands to action are being called in containerAction, and I am able to display logs created by that action, but only once it is complete. This seems not all that useful, so I'm still looking for a way to have the logs stream.

**Comment by coffeepac** [comment]
there should be an option for how you access the STDOUT variable in Command.  Possibly by buffer type.

**Comment by DStorck** [comment]
got it working, current implementation is using the docker go client with containerLogs, hopefully PR forthcoming

**Comment by coffeepac** [comment]
sweet!

**Comment by DStorck** [comment]
Log stream now working well.  When this goes through it will close https://github.com/samsung-cnct/k2cli/issues/17, which asked for an update to the keep-alive flag
