### ISSUE TITLE
add k2cli cluster upgrade 

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2cli#70]
now that k2 has master node upgrade functionality, users should be able to run `k2cli cluster upgrade` to fire off upgrade.sh

**Comment by coffeepac** [comment]
I think this is a dupe of #6  Mostly because I think the easiest way to implement the changes to non-master nodePools will be to extend the work you did to target any nodePool by name instead of being set to the master pool

**Comment by coffeepac** [comment]
blocked until all nodePools can be upgraded in k2

**Comment by guineveresaenger** [comment]
PR: #98
