### ISSUE TITLE
Update Readme.md information to match new configuration

### ISSUE THREAD

**Issue by NathanZook** [samsung-cnct/k2cli#72]
Specifically, the references in "Building a configuration file".  Perhaps some later references as well.

**Comment by DStorck** [comment]
This ticket is covering READMEs as lots of other documentation that has examples from the old config style.

**Comment by coffeepac** [comment]
@DStorck what should I be reviewing for this issue?

**Comment by DStorck** [comment]
closed by https://github.com/samsung-cnct/k2/pull/380
