### ISSUE TITLE
short term fix for multiple clusters in config file

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2cli#76]
we need a short term fix for the new config in k2cli.  currently there is a hack proposed ( #74 ) but that only works if there is only one cluster in the config file.  we need to have the ability to have several clusters listed and to be able to select which cluster we will operate on.   

options:
- if no cluster flag is set then perform the operation on all clusters 
- if no cluster flag is set then operate on the first cluster in the list (could be unstable as the Viper unmarhalling may not be consisten across invocations)
- if no cluster flag is set then quit and ask the user to specify a cluster (by using the --cluster flag which doesn't exist yet)

**Comment by DStorck** [comment]
reminder that as soon as we allow users to specify multiple clusters in the config we need to remove the check done in https://github.com/samsung-cnct/k2/pull/417 because `up` right now would fail immediately

**Comment by coffeepac** [comment]
handled in k2
