### ISSUE TITLE
create CI job for k2cli

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2cli#79]
k2cli should be getting built and published via a Jenkinsfile in the new CI system.  This Jenkinsfile should:
- build/test all PRs
- publish a new 'HEAD' version of k2cli whenever a PR gets pushed to master

This job should not
- push a new major or minor version of k2cli.  that will remain a manual process until we have a common story for versioning across projects.

**Comment by guineveresaenger** [comment]
From [k2  #189](https://github.com/samsung-cnct/k2/issues/189), the steps are:

- create a multibranch project in jenkins
- need to use some auth
- specify the owner/project
- add a Jenkinsfile to the project
- add a webhook to the project in github that points to https://common-jenkins.kubeme.io/github-webhook/

Is this still accurate?

**Comment by coffeepac** [comment]
yes.  and please add the final bullet point to the CI page in the wiki.  i had forgotten about it.

**Comment by guineveresaenger** [comment]
will do

**Comment by coffeepac** [comment]
would also like to see this job spin a cluster up, change the version of a nodepool (special so its fast, only 2 nodes) and then spin the cluster down.

**Comment by coffeepac** [comment]
hit a problem where the boto client needs an env var set so it can find the credentials file in a non-standard location.

**Comment by coffeepac** [comment]
okay!  trial and tribulations but back onto this.  the job is kind of working, going to probably follow the layout of the new K2 Jenkinsfile, keep some history around.

**Comment by coffeepac** [comment]
add a step to generate the docs  https://github.com/samsung-cnct/k2cli/issues/91

**Comment by coffeepac** [comment]
https://github.com/samsung-cnct/k2cli/issues/102

**Comment by coffeepac** [comment]
not going to use the go-tools makefile for now, it doesn't look like it will integrate easily with our Jenkins DinD scenario in Kubernetes

**Comment by coffeepac** [comment]
Current status:  currently running/publishing junit tests and spinning up AWS & GKE clusters.

Left to do:  
- execute the doc generation step to ensure the docs are up-to-date
  - I'm not sure how to do this exactly, so its a bit of exploration
- run `gosimple` as part of the 'Test: Unit' step.  
  - might need to install gosimple into the custom golang container.  see issue #102 

Optional step:
- decide if altering the version of a nodePool is something to be done as part of CI 
  - takes awhile
  - not sure how we would verify this, the verification steps I'm thinking of are fragile

**Comment by guineveresaenger** [comment]
Status update @patthec:

It looks like `gosimple` is all set up. Some messy bits in the CI run, but they seem unrelated. (Test:Unit step passes CI.)

For the doc generation step: 
The way to manually generate new docs is simply to run `k2cli docs docs`.

What is the definition of up-to-date docs? Do we check the date of the last doc generation and compare to present date? Or do we look at which cmd/ files changed (somehow) and see if there is a corresponding update to the docs?
Should we require each PR to have newly generated docs? The current ones are from November of last year.
What is the point of doing this in CI, since we'd be doing it inside k2-tools container (and the shiny new docs vanish afterward)? 
Generating docs is currently a manual step. This means that inherently they are almost never up to date.

**Comment by guineveresaenger** [comment]
I imagine what I _could_ do is generate docs in a folder _other_ than `docs/` and then cat each individual file and compare to the ones present in `docs/`?

**Comment by guineveresaenger** [comment]
@coffeepac also I'm curious about cutting a release when master completes (as perdiscussion yesterday) - can you clarify?

**Comment by davidewatson** [comment]
You should be able to run `make gh-pages` to regenerate the docs. I just tried and the documentation source in `sphinx/index.rst` is broken.

**Comment by guineveresaenger** [comment]
Looking into this further, it appears as though running a simple docs gen inside CI is not going to work, as the docs generation is user specific. (The current docs have a team member's local default filepaths. Which isn't terrible, but a bit weird and probably inaccurate.)

Suggestion: Skip verification step and just update the autogen every time we merge into master.
@coffeepac comments?

**Comment by coffeepac** [comment]
Probably best to update the autogenerated docs as part of the merge to master.  I don't like that answer because we're pushing to master but it works.  we will need to be very, very careful about it.

**Comment by guineveresaenger** [comment]
how would one go about making the autogenerated docs automatic with a merge? that's not a CI job is it?

**Comment by coffeepac** [comment]
you'd have to hardcode some git commands.  and this is going to be a much bigger issue then I expected.  I'd like this done so probably re-open #91 and leave it for now.

**Comment by guineveresaenger** [comment]
As per https://github.com/samsung-cnct/k2cli/issues/52 the documentation will not currently be a part of CI.

**Comment by guineveresaenger** [comment]
As per discussion on slack, we will not currently be cutting releases with CI.

**Comment by guineveresaenger** [comment]
Currently: 
- gosimple added to Jenkinsfile
- helm_override is set to false during CI for each cluster, so CI will continue.

**Comment by guineveresaenger** [comment]
I am wondering if the tests that are not passing are specifically not passing for CI runs because it looks to me like CI has a different config file path?

**Comment by guineveresaenger** [comment]
Tests were failing because of JUnit. This will be addressed later.
ToReview: make sure CI passes on current master.
