### ISSUE TITLE
Confirm overwriting on generate if config already exists

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#89]
```
$ k2cli generate -k $PWD/staging.yaml
Pulling image 'quay.io/samsung_cnct/k2:latest' ███▒▒▒▒▒▒▒ Complete
Generated aws config at /home/jjulian/.kraken/config.yaml
```
This overwrote the existing config.yaml in that directory. I would expect it to not overwrite a config file but, instead, ask me if I did want it overwritten.

**Comment by leahnp** [comment]
@joejulian @coffeepac should the expected behavior be: in the event there is already a config file, user is asked if they want to continue and overwrite or stop, if yes - continue and overwrite, if no - stop process and print message that user should manually address the problem?

**Comment by alejandroEsc** [comment]
Why not just stop the process if file exist, display an error indicating that the file already exists and stop the process. Let the user decide if they want to override by changing the file name or deleting.

**Comment by joejulian** [comment]
What @alejandroEsc said. y/n questions are too easily flubbed.

**Comment by leahnp** [comment]
Copy that, thank you

**Comment by leahnp** [comment]
https://github.com/samsung-cnct/k2cli/pull/115
