### ISSUE TITLE
k2cli documentation is outdated 

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2cli#91]
currently https://github.com/samsung-cnct/k2cli/tree/master/docs are auto-generated, but badly outdated. Several flags are incorrect, and if we are going to have these docs continue to be auto-generated, it should be automated to update whenever the code changes.

**Comment by coffeepac** [comment]
should be done as part of the release process

**Comment by coffeepac** [comment]
if we wanted to have a CI test for the docs being up to date, that could be done.  but generation of the docs still needs to be done by the end user on the original PR.

**Comment by coffeepac** [comment]
blocked by not having a k2cli pipeline

**Comment by guineveresaenger** [comment]
Per discussion in #79 it was deemed a good idea to reopen this ticket. We should automatically generate docs when code gets merged to master.
