### ISSUE TITLE
k2cli tools kubectl error

### ISSUE THREAD

**Issue by joejulian** [samsung-cnct/k2cli#92]
I'm getting an unintelligible error attempting to use `k2cli tools`
```
$ k2cli tool kubectl --config /home/jjulian/dev/cnct/rc/staging-cluster/config.yaml get namespaces 
Using K2 config file: /home/jjulian/dev/cnct/rc/staging-cluster/config.yaml
error: group map[:0xc8203bee00 authorization.k8s.io:0xc8203bf030 autoscaling:0xc8203bf0a0 batch:0xc8203bf260 rbac.authorization.k8s.io:0xc8204fc0e0 storage.k8s.io:0xc8204fc150 federation:0xc8203be930 apps:0xc8203bee70 authentication.k8s.io:0xc8203beee0 certificates.k8s.io:0xc8203bf2d0 componentconfig:0xc8203bf340 extensions:0xc8204fc000 policy:0xc8204fc070] is already registered
error: group map[:0xc8203bee00 authorization.k8s.io:0xc8203bf030 autoscaling:0xc8203bf0a0 batch:0xc8203bf260 rbac.authorization.k8s.io:0xc8204fc0e0 storage.k8s.io:0xc8204fc150 federation:0xc8203be930 apps:0xc8203bee70 authentication.k8s.io:0xc8203beee0 certificates.k8s.io:0xc8203bf2d0 componentconfig:0xc8203bf340 extensions:0xc8204fc000 policy:0xc8204fc070] is already registered
```
The same command using kubectl 1.6.4 works:
```
$ sudo kubectl --kubeconfig ~/.kraken/staging/admin.kubeconfig get namespaces
NAME              STATUS    AGE
default           Active    11m
kube-auth         Active    8m
kube-networking   Active    8m
kube-public       Active    11m
kube-system       Active    11m
```

**Comment by davidewatson** [comment]
Is it possible that `--config` is being passed to kubectl instead of interpreted by k2cli? I.e. what happens if you try `k2cli tool --config ~/.kraken/config.yaml kubectl get namespaces`?

**Comment by joejulian** [comment]
No luck. I tried moving it there and before tool. Always get the same error.

**Comment by davidewatson** [comment]
Nack, it works both ways.

**Comment by joejulian** [comment]
If it's working for you, then it may have something to do with oidc maybe.

**Comment by joejulian** [comment]
It could also be a yaml parse failure. I created (and referenced) new anchors while leaving the defaults behind:
```
   - &defaultKeyPair
      name: defaultKeyPair
      kind: keyPair
      publickeyFile: "$HOME/.ssh/id_rsa.pub"
      privatekeyFile: "$HOME/.ssh/id_rsa"
   - &stagingKeyPair
      name: stagingKeyPair
      kind: keyPair
      publickeyFile: "/home/jjulian/dev/cnct/rc/staging-cluster/aws_staging.rsa.pub"
      privatekeyFile: "/home/jjulian/dev/cnct/rc/staging-cluster/aws_staging.rsa"
```

**Comment by alejandroEsc** [comment]
I have seen that issue when either configuration is wrong/cert is wrong, or you arent authorized. I have a question. I never understood `k2cli tools kubectl --config` does this update your kubectl with the config you point it to?

**Comment by coffeepac** [comment]
This error is typically due to using the wrong version of kubectl with kubernetes.  `k2cli tool kubectl` will use kubectl v1.4.x right now.  waiting on #86 to merge.  we will then need a release which I can do when that's merged.

**Comment by alejandroEsc** [comment]
I can confirm @coffeepac, I think solution here is to create a kubectl-vm and allow users to select version, probably a scrip that creates a symbolic link to the version you want to use would help.

**Comment by coffeepac** [comment]
@alejandroEsc the issue I linked will execute the outcome you want based on the K2 config file.  When #86 is closed you should try this again and make sure it works.

**Comment by coffeepac** [comment]
this will work when kubectl tool works (find issue, put it here)

**Comment by coffeepac** [comment]
fixed.
