### ISSUE TITLE
Instructions for using tool command misses path to config file in README

### ISSUE THREAD

**Issue by guineveresaenger** [samsung-cnct/k2cli#96]
"To see all installed applications across all namespaces:
```
./k2cli tool kubectl -- get pods --all-namespaces
```"
should have a specified config file path after the `--` and before the `get pods`. Given that the tool commands do not take dashes, this should be fixed.

**Comment by coffeepac** [comment]
dashes like that are typically used to mark when an application should stop parsing the cli inputs and simply pass the rest of the options on.  in this case, we do not want k2cli to parse `get pods --all-namespaces`, we want k2cli to pass those arguments on without being touched.

do you get an error when you use the double dash?

**Comment by guineveresaenger** [comment]
![screen shot 2017-06-28 at 2 03 38 pm](https://user-images.githubusercontent.com/13116240/27660083-af6f6e96-5c0a-11e7-9ed4-d8c73949ae25.png)

I guess I'm confused why the top line points at a config file, and the socnd one does not. It looked like a typo/forgetting to me. It appears otherwise? Also, this is difficult to test because the tools are currently not working.

**Comment by coffeepac** [comment]
ahh, okay.  the config should be listed for consistency's sake.  I'll just do this now.
