### ISSUE TITLE
`k2cli tool kubectl` with No Arguments Causes Go Panic

### ISSUE THREAD

**Issue by sostheim** [samsung-cnct/k2cli#99]
Post successful cluster up, inadvertently ran truncated command that cause a panic.

```
$ k2cli tool kubectl 
Using K2 config file: /Users/sostheim/.kraken/config.yaml
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
github.com/samsung-cnct/k2cli/cmd.getContainerName(0x145f580, 0xc4203336e0)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/cmd/container_helpers.go:473 +0x138
github.com/samsung-cnct/k2cli/cmd.containerEnvironment(0xc4202d62a0, 0x23, 0xc4202a4c00)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/cmd/container_helpers.go:142 +0x34
github.com/samsung-cnct/k2cli/cmd.containerAction(0xc4202cb960, 0x1705fe0, 0xc420316c60, 0xc4203621a0, 0x1, 0x1, 0xc4202d62a0, 0x23, 0x0, 0x0, ...)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/cmd/container_helpers.go:324 +0xc5
github.com/samsung-cnct/k2cli/cmd.glob..func12(0x173ccc0, 0x1761310, 0x0, 0x0)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/cmd/kubectl.go:53 +0x361
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).execute(0x173ccc0, 0x1761310, 0x0, 0x0, 0x173ccc0, 0x1761310)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:636 +0x231
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x173bde0, 0x100649c, 0xc420076058, 0x0)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:722 +0x339
github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra.(*Command).Execute(0x173bde0, 0x0, 0x47)
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/vendor/github.com/spf13/cobra/command.go:681 +0x2b
github.com/samsung-cnct/k2cli/cmd.Execute()
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/cmd/root.go:65 +0x31
main.main()
	/Users/pat/code/go/src/github.com/samsung-cnct/k2cli/main.go:23 +0x22
```

Using brew installed version of `k2cli` and Go 1.8.1:

```
$ which k2cli
/usr/local/bin/k2cli

$ k2cli version
1.0.5-alpha+git.sha.e04ae0d98289565ab71424fd7b83072bfaed8f66

$ go version
go version go1.8.1 darwin/amd64
```

**Comment by sostheim** [comment]
help subcommand works fine.

```
$ k2cli tool kubectl --help
Use Kubernetes kubectl with the K2 
	cluster configured by the specified yaml file

Usage:
  k2cli tool kubectl [flags]

Global Flags:
  -c, --config string        Location of the k2config (default "/Users/sostheim/.kraken/config.yaml")
  -d, --docker-host string   docker host address (default "unix:///var/run/docker.sock")
  -i, --image string         k2 container image (default "quay.io/samsung_cnct/k2:latest")
  -k, --k2config string      config file for k2cli (default "/Users/sostheim/.k2cli.yaml")
  -a, --keep-alive           keep stopped containers.
  -w, --log-path string      Save output output of container action to path
  -x, --log-success          Display full action logs on success
  -o, --output string        K2 output folder (default "/Users/sostheim/.kraken")
  -t, --timeout int          timeout (in seconds) for container actions (default 1200)
  -v, --verbosity            Verbose output
```

**Comment by NathanZook** [comment]
What is in your `.kraken/config.yaml` file?

**Comment by mikeln** [comment]
Relavent Code:   
```
func getContainerName() string {
        // only supports first cluster name right now
        clusters := clusterConfig.Get("deployment.clusters")
        if clusters != nil {
                firstCluster := clusters.([]interface{})[0].(map[interface{}]interface{})
                return os.ExpandEnv(firstCluster["name"].(string))                <--- error line
        } else {
                return "cluster-name-missing"
        }
}
```
A couple of items:
1) not this problem, but the `return "cluster-name-missing"` is not correct.  That return will only get tripped if `deployment.clusters` is not in the yaml file.
2) the error could be that `firstCluster` is `nil`, or that it is not `nil`, but the key `"name"` does not exist in the `firstCluster` map.
3) to actually return the correct errors...like `cluster-name-missing`, we need to eval `firstCluster["name"]` return before attempting to type cast and expand it.
4) This code makes a lot of assumptions in 2 lines on the format of the data structure, without a way to handle a badly formatted structure.  Some type of general format error catch should be used.

**Comment by mikeln** [comment]
The "real" problem is that `cmd/kubectl.go` does not execute a "usage" type when no additional commands are present.  I assume that kubectl should require subcommands, and never be valid by itself.

**Comment by sostheim** [comment]
I just ran `kubctl` w/o arguments as a stand alone tool and it assumes that as valid and dumps the usage/help statement.

**Comment by mikeln** [comment]
the k2cli should do something similar...is my point.   It isn't set up in the code.

**Comment by sostheim** [comment]
Yeah, I got that, was just acking your sentiment with an observed behavior.

**Comment by NathanZook** [comment]
The tool subcommand specifies a default value for the config file.  https://github.com/samsung-cnct/k2cli/blob/master/cmd/tool.go#L39-L43.  The error is presumably saying that the nil interface cannot be made into a string.  This would be because the fetch of `firstCluster["name"]` returned a nil.  Which would suggest that the error is occurring because the name was not specified in the cluster.  This section of code can only be entered if `deployments.clusters` resolves, so there must have been something to read.  I really expect that there is a config file at `$HOME/.kraken/config.yaml`, and that the name of the first cluster has not been set.

**Comment by alejandroEsc** [comment]
This issue should have been addressed on my refactoring PR and my current tests suggests they are. Please report any further issues if they appear or if the issue persists.
